#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────
// extract-script.js — print the deployable Apps Script, from the file
// the tests actually check.
//
//   node tutor-sheet/extract-script.js            > /tmp/rw.gs
//   node tutor-sheet/extract-script.js math       > /tmp/math.gs
//
// WHY THIS EXISTS
// There used to be a checked-in `rw-apps-script.gs` beside the markdown.
// Nothing deployed it and nothing tested it, so when R&W's `Prediction`,
// `On text` and `On options` columns were added, they were added THERE —
// because adding them to the tested file would have failed an assertion
// that was itself wrong. The predictions the class reviews together went
// nowhere for months, and the sheet looked fine the whole time.
// apps-script.test.js still carries the note.
//
// So there is deliberately no second copy in this repo. The markdown is
// the source of truth, the test parses the same block this prints, and
// this is how you get a paste-able file when you need one — regenerate
// it, never edit it.
//
// It uses the SAME extraction the test uses: the first ```javascript
// block in the markdown. If that ever stops matching, the test stops
// testing the deployed script, so this asserts the block is non-trivial
// and parses before printing anything.
// ─────────────────────────────────────────────────────────────────
'use strict';
const fs   = require('fs');
const path = require('path');
const vm   = require('vm');

const WHICH = (process.argv[2] || 'rw').toLowerCase();
const FILES = { rw: 'rw-apps-script.md', math: 'math-apps-script.md' };
const md    = FILES[WHICH];
if (!md) {
    console.error('usage: node tutor-sheet/extract-script.js [rw|math]');
    process.exit(2);
}

const file = path.join(__dirname, md);
if (!fs.existsSync(file)) {
    console.error('no such file: ' + file);
    process.exit(2);
}

const m = fs.readFileSync(file, 'utf8').match(/```javascript\n([\s\S]*?)```/);
if (!m) {
    console.error(md + ': no ```javascript block — apps-script.test.js reads the '
                + 'same one, so it is not testing the deployed script either.');
    process.exit(1);
}
const code = m[1];

// A silent half-extraction is worse than none: it would be pasted over a
// working deployment. Fail loudly instead.
if (code.length < 2000 || !/function doPost/.test(code)) {
    console.error(md + ': the extracted block is ' + code.length
                + ' bytes and has no doPost — extraction is wrong.');
    process.exit(1);
}
try {
    new vm.Script(code, { filename: md });
} catch (e) {
    console.error(md + ': the extracted block does not parse — ' + e.message);
    process.exit(1);
}

process.stdout.write(
    '// GENERATED from tutor-sheet/' + md + ' by tutor-sheet/extract-script.js.\n'
  + '// Do not edit this file. Edit the markdown, run the tests, regenerate.\n\n'
  + code);
